### ISSUE TITLE
Project actively developed?

### ISSUE THREAD

**Issue by onitreb** [abhshkdz/HackFlowy#14]
Hi!  I love the idea of this project.  Workflowy charges a lot for premium membership.

I'm just wondering if it's still in development.  
How 'functional' is it in its current state?
Is anyone using it full time?  
How do the features compare to Workflowy?
Can it be run on a shared hosting account, like on Dreamhost?

**Comment by jeffszusz** [comment]
I was thinking of starting something like this, if only because I'm paranoid workflowy will go out of business and disappear...

If I can find the time, I might fork and hack on this a bit. Do you prefer all contributions to push forward toward a workflowy clone, or are "new" features possibly welcome?

**Comment by abhshkdz** [comment]
I'd prefer if we first get the Workflowy feature-set working smoothly. But if you do have a good feature suggestion, feel free to open an issue / hack on it.

**Comment by onitreb** [comment]
As a side note: once I hit my free limit on Workflowy I moved over to Diigo outliner. It's a clone of Workflowy, more or less, and has no monthly line limit. And you can have multiple lists.

Can Diigo go out of business? I don't really know how they're still in business, but I've been using them since 2007 and they're still chugging along. :)

**Comment by buduguru** [comment]
I would recommend to try Checkvist. Good alternative and no limits for list items. They have better keyboard shortcuts too.
